#ifndef DISTRHO_PLUGIN_INFO_H_INCLUDED
#define DISTRHO_PLUGIN_INFO_H_INCLUDED

#define DISTRHO_PLUGIN_BRAND   "venom"
#define DISTRHO_PLUGIN_NAME    "venom"
#define DISTRHO_PLUGIN_URI     "https://github.com/ih8bxngus/venom"
#define DISTRHO_PLUGIN_CLAP_ID "com.venom.synth"

#define DISTRHO_PLUGIN_HAS_UI          1
#define DISTRHO_PLUGIN_IS_RT_SAFE      1
#define DISTRHO_PLUGIN_IS_SYNTH        1
#define DISTRHO_PLUGIN_WANT_MIDI_INPUT 1
#define DISTRHO_PLUGIN_WANT_STATE      1
#define DISTRHO_PLUGIN_WANT_FULL_STATE 1
#define DISTRHO_PLUGIN_NUM_INPUTS      0
#define DISTRHO_PLUGIN_NUM_OUTPUTS     2

#define DISTRHO_UI_USE_NANOVG     1

#define DISTRHO_UI_DEFAULT_WIDTH  960
#define DISTRHO_UI_DEFAULT_HEIGHT 790

#endif // DISTRHO_PLUGIN_INFO_H_INCLUDED
